### ISSUE TITLE
issues with the new 2D advection-diffusion example

### ISSUE THREAD

**Issue by slayoo** [atmos-cloud-sim-uj/MPyDATA#453]
@pawelmagnu, here's an update on the post-merge status for #427:  

- [x] animation is not properly uploaded to "tip" release (file not found error in the logs) - this blocks upload to PyPI
- [x] when executing on mybinder.org, there is "ModuleNotFoundError: No module named 'imageio'" error
- [x] Colab badge in the notebook has wrong URL
- [x] there is no link/badge in the examples/README.md leading to the new examples
- [x] figures in the notebook are not displayed when viewed on GitHub - there are just blank white panels
- [x] no "view on github" badge in the notebook
- [x] some header comment with a hint on what is being computed in the notebook would be very helpful

Let's aim at fixing it next week

**Comment by pawelmagnu** [comment]
@Kojec1 could you check which points have already been addressed in #456 ?

**Comment by Kojec1** [comment]
There's still an issue with the figures displayed on GitHub, missing header information and I haven't managed to check if the .gif file is successfully uploaded to the "tip" release. The other issues seem to be solve.

**Comment by pawelmagnu** [comment]
I'm pretty sure we can't check if the .gif file uploads before actually merging to main.

**Comment by slayoo** [comment]
.gif file upload works!
The notebook does not work on Colab yet as it fails on first line with:
![image](https://github.com/user-attachments/assets/b0f3af04-4af6-454b-b07b-97d43d39ca65)
This is due to lack of `pip install ...` commands for Colab in an initial notebook cell, like we do in other notebooks.
Here's a PR addressing it: https://github.com/open-atmos/PyMPDATA/pull/458

**Comment by slayoo** [comment]
Just tested both on Colab and mybinder.org, and everything works!
So, we're still missing two things:
- [x]  figures in the notebook are not displayed when viewed on GitHub - notebook was committed with cell output cleared
- [x]  some header comment with a hint on what is being computed in the notebook would be very helpful

**Comment by pawelmagnu** [comment]
addressed in #462

**Comment by slayoo** [comment]
kudos!
